/**
 * Auto-generated by scripts/generate-drink-asset-manifest.mjs
 * Do not edit manually.
 */

export const GENERATED_DRINK_ASSET_MANIFEST = {
  "bellini": {
    "diaryIndices": [
      1,
      2,
      3,
      4,
      5
    ],
    "hasRecord": true
  },
  "gin-tonic": {
    "diaryIndices": [
      1
    ],
    "hasRecord": true
  },
  "hot-cocoa": {
    "diaryIndices": [
      1,
      2,
      3,
      4
    ],
    "hasRecord": true
  },
  "irish-coffee": {
    "diaryIndices": [
      1
    ],
    "hasRecord": true
  },
  "koshu": {
    "diaryIndices": [
      1,
      2,
      3,
      4
    ],
    "hasRecord": true
  },
  "negroni": {
    "diaryIndices": [
      1
    ],
    "hasRecord": true
  },
  "old-fashioned": {
    "diaryIndices": [
      1,
      2,
      3,
      4
    ],
    "hasRecord": true
  },
  "yamazaki-12": {
    "diaryIndices": [
      1
    ],
    "hasRecord": true
  }
} as const;
