/**
 * Auto-generated by scripts/generate-ios-sfx-manifest.mjs
 * Do not edit manually.
 */
export const IOS_SFX_FILE_AVAILABLE = {
  click: true,
  door: true,
  glassSlide: true,
} as const satisfies Record<"click" | "door" | "glassSlide", boolean>;
