/**
 * Auto-generated by scripts/generate-ios-sfx-manifest.mjs
 * Do not edit manually.
 */
/** Safari / HTMLAudioElement pool — ios 音源再生成時に bump する */
export const IOS_SFX_CACHE_REVISION = 14;

export const IOS_SFX_FILE_AVAILABLE = {
  click: true,
  door: true,
  glassSlide: true,
  send: true,
  menuOpen: true,
  menuClick: true,
  page: true,
  think: true,
} as const satisfies Record<"click" | "door" | "glassSlide" | "send" | "menuOpen" | "menuClick" | "page" | "think", boolean>;

/** ビルド時の実ファイルサイズ — SE3 fetch 証明ログと照合 */
export const IOS_SFX_FILE_BYTE_LENGTH = {
  click: 4124,
  door: 67201,
  glassSlide: 40850,
  send: 20476,
  menuOpen: 33476,
  menuClick: 14727,
  page: 17563,
  think: 42721,
} as const satisfies Record<"click" | "door" | "glassSlide" | "send" | "menuOpen" | "menuClick" | "page" | "think", number>;

/** ビルド時の mtime（ISO） — Last-Modified 照合用 */
export const IOS_SFX_FILE_LAST_MODIFIED = {
  click: "2026-07-05T16:34:40.404Z",
  door: "2026-07-05T16:34:40.406Z",
  glassSlide: "2026-07-05T16:34:40.407Z",
  send: "2026-07-05T16:34:40.410Z",
  menuOpen: "2026-07-05T16:34:40.409Z",
  menuClick: "2026-07-05T16:34:40.408Z",
  page: "2026-07-05T16:34:40.409Z",
  think: "2026-07-05T16:34:40.410Z",
} as const satisfies Record<"click" | "door" | "glassSlide" | "send" | "menuOpen" | "menuClick" | "page" | "think", string | null>;
